"""add_mission_columns

Revision ID: 0dc700efe0b1
Revises: eab2f634a829
Create Date: 2026-02-04 14:18:22.399720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc700efe0b1'
down_revision = 'eab2f634a829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenances', schema=None) as batch_op:
        batch_op.alter_column('kilometrage',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('prochain_entretien_km',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titre', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('priorite', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('distance_prevue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nombre_colis', sa.Integer(), nullable=True))

    with op.batch_alter_table('planning', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True))

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_column('nombre_colis')
        batch_op.drop_column('distance_prevue')
        batch_op.drop_column('priorite')
        batch_op.drop_column('titre')

    with op.batch_alter_table('maintenances', schema=None) as batch_op:
        batch_op.alter_column('prochain_entretien_km',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('kilometrage',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
