"""Add expiry alert tracking to Compliance model

Revision ID: 1c808e5833be
Revises: b6cb21a76b4e
Create Date: 2026-01-22 13:43:49.360831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c808e5833be'
down_revision = 'b6cb21a76b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compliance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_alert_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('expiry_alert_sent_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_missions_created_by_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_missions_created_by_id', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('compliance', schema=None) as batch_op:
        batch_op.drop_column('expiry_alert_sent_at')
        batch_op.drop_column('expiry_alert_sent')

    # ### end Alembic commands ###
