"""Add prochaine_entretien_prevu to maintenance

Revision ID: 2933eed98a3b
Revises: 7eb02681e8ba
Create Date: 2025-12-19 14:16:35.245594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2933eed98a3b'
down_revision = '7eb02681e8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prochaine_entretien_prevu', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenances', schema=None) as batch_op:
        batch_op.drop_column('prochaine_entretien_prevu')

    # ### end Alembic commands ###
