"""initial schema

Revision ID: 43cd88bd4a8f
Revises: 
Create Date: 2025-12-16 15:06:38.970171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cd88bd4a8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('marque', sa.String(length=100), nullable=False),
    sa.Column('modele', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('puissance', sa.Integer(), nullable=False),
    sa.Column('date_acquisition', sa.Date(), nullable=False),
    sa.Column('date_mise_en_circulation', sa.Date(), nullable=False),
    sa.Column('kilometrage', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('affectation', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule')
    )
    op.create_table('action_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entite', sa.String(length=50), nullable=False),
    sa.Column('entite_id', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('permis', sa.String(length=100), nullable=False),
    sa.Column('date_embauche', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('vehicule_assigne_id', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['vehicule_assigne_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicule_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kilometrage', sa.Integer(), nullable=False),
    sa.Column('cout', sa.Float(), nullable=True),
    sa.Column('prestataire', sa.String(length=255), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('demandeur_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['demandeur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicule_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('kilometrage', sa.Integer(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('cout', sa.Float(), nullable=False),
    sa.Column('station', sa.String(length=255), nullable=False),
    sa.Column('conducteur_id', sa.String(), nullable=False),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['conducteur_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('vehicule_id', sa.String(), nullable=False),
    sa.Column('conducteur_id', sa.String(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('kilometrage_depart', sa.Integer(), nullable=True),
    sa.Column('kilometrage_arrivee', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['conducteur_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicule_id', sa.String(), nullable=False),
    sa.Column('conducteur_id', sa.String(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['conducteur_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planning')
    op.drop_table('missions')
    op.drop_table('fuel_entries')
    op.drop_table('maintenances')
    op.drop_table('drivers')
    op.drop_table('action_logs')
    op.drop_table('vehicles')
    op.drop_table('users')
    # ### end Alembic commands ###
