"""add fuel new columns

Revision ID: 7eb02681e8ba
Revises: 9cfc81edb7f2
Create Date: 2025-12-18 16:51:13.807188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb02681e8ba'
down_revision = '9cfc81edb7f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_ticket', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('solde_ticket', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('montant_ristourne', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('montant_transaction_annuler', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('distance_possible_restant', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('capacite_reservoir', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('alerte', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entries', schema=None) as batch_op:
        batch_op.drop_column('alerte')
        batch_op.drop_column('capacite_reservoir')
        batch_op.drop_column('distance_possible_restant')
        batch_op.drop_column('montant_transaction_annuler')
        batch_op.drop_column('montant_ristourne')
        batch_op.drop_column('solde_ticket')
        batch_op.drop_column('numero_ticket')

    # ### end Alembic commands ###
