"""refactor_mission_schema

Revision ID: 9c8abc69253d
Revises: da8cc44846a5
Create Date: 2025-12-18 14:25:02.104672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c8abc69253d'
down_revision = 'da8cc44846a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add new columns as nullable first
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('missionnaire', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('heure_depart', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('heure_retour', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lieu_depart', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lieu_destination', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kilometrage_retour', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kilometre_parcouru', sa.Integer(), nullable=True))

        # Handle date changes (postgres specific in original script, but general here)
        # We'll just define them as Date, let sqlalchemy handle backend specifics if possible
        # Or keep original logic if it was working for the target DB
    
    # 2. Data Migration
    # Generate reference
    op.execute("UPDATE missions SET reference = 'MIS-' || SUBSTR(id, 1, 8)")
    
    # Migrate status to state (map old values if needed, or just copy)
    # Assuming old 'statut' values map broadly to 'state' or using default
    op.execute("UPDATE missions SET state = 'nouveau' WHERE statut IS NULL")
    op.execute("UPDATE missions SET state = statut WHERE statut IS NOT NULL")
    
    # Migrate destination
    op.execute("UPDATE missions SET lieu_destination = destination")
    op.execute("UPDATE missions SET lieu_depart = 'Siège' WHERE lieu_depart IS NULL")
    
    # 3. Apply constraints and cleanup
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.alter_column('reference', nullable=False)
        batch_op.alter_column('state', nullable=False)
        batch_op.alter_column('lieu_depart', nullable=False)
        batch_op.alter_column('lieu_destination', nullable=False)
        
        batch_op.create_unique_constraint(None, ['reference'])
        
        # Date column alterations
        # Note: SQLite doesn't support altering column types easily, but Alembic batch tries.
        # If this fails on SQLite, we might need to ignore or do complex moves.
        # For now, we trust batch mode.
        batch_op.alter_column('date_debut', type_=sa.Date())
        batch_op.alter_column('date_fin', type_=sa.Date(), nullable=True)

        batch_op.drop_column('description')
        batch_op.drop_column('statut')
        batch_op.drop_column('titre')
        batch_op.drop_column('destination')
        batch_op.drop_column('kilometrage_arrivee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kilometrage_arrivee', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('destination', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('titre', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('statut', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('date_fin',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('date_debut',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('kilometre_parcouru')
        batch_op.drop_column('kilometrage_retour')
        batch_op.drop_column('lieu_destination')
        batch_op.drop_column('lieu_depart')
        batch_op.drop_column('heure_retour')
        batch_op.drop_column('heure_depart')
        batch_op.drop_column('state')
        batch_op.drop_column('missionnaire')
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
