"""refactor_fuel_schema

Revision ID: 9cfc81edb7f2
Revises: 9c8abc69253d
Create Date: 2025-12-18 16:04:59.371540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfc81edb7f2'
down_revision = '9c8abc69253d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heure', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('produit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('precedent_km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actuel_km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('km_parcouru', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('prix_unitaire', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ancien_solde', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('montant_recharge', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quantite_rechargee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bonus', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_achete', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quantite_achetee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cout_au_km', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('consommation_100', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('distance_possible', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nouveau_solde', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quantite_restante', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('difference_solde', sa.Float(), nullable=True))
        batch_op.alter_column('station',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('kilometrage',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('cout',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_entries', schema=None) as batch_op:
        batch_op.alter_column('statut',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('cout',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('volume',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('kilometrage',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('station',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('difference_solde')
        batch_op.drop_column('quantite_restante')
        batch_op.drop_column('nouveau_solde')
        batch_op.drop_column('distance_possible')
        batch_op.drop_column('consommation_100')
        batch_op.drop_column('cout_au_km')
        batch_op.drop_column('quantite_achetee')
        batch_op.drop_column('total_achete')
        batch_op.drop_column('bonus')
        batch_op.drop_column('quantite_rechargee')
        batch_op.drop_column('montant_recharge')
        batch_op.drop_column('ancien_solde')
        batch_op.drop_column('prix_unitaire')
        batch_op.drop_column('km_parcouru')
        batch_op.drop_column('actuel_km')
        batch_op.drop_column('precedent_km')
        batch_op.drop_column('produit')
        batch_op.drop_column('heure')

    # ### end Alembic commands ###
