"""Add mileage alert fields to vehicle

Revision ID: cb8582533ea9
Revises: ff747e9504e6
Create Date: 2025-12-19 15:00:56.600400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8582533ea9'
down_revision = 'ff747e9504e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vidange_interval_km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_vidange_km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vidange_alert_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('filtre_interval_km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_filtre_km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('filtre_alert_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('filtre_alert_sent')
        batch_op.drop_column('last_filtre_km')
        batch_op.drop_column('filtre_interval_km')
        batch_op.drop_column('vidange_alert_sent')
        batch_op.drop_column('last_vidange_km')
        batch_op.drop_column('vidange_interval_km')

    # ### end Alembic commands ###
