"""Add image_facture to maintenance table

Revision ID: da8cc44846a5
Revises: 3b169e92635e
Create Date: 2025-12-18 13:22:41.186622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8cc44846a5'
down_revision = '3b169e92635e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_facture', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenances', schema=None) as batch_op:
        batch_op.drop_column('image_facture')

    # ### end Alembic commands ###
