"""Refactor Vehicle schema

Revision ID: ddd63b7d3bde
Revises: dd096c0a2a19
Create Date: 2025-12-18 09:08:35.798041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd63b7d3bde'
down_revision = 'dd096c0a2a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_128', sa.String(length=255), nullable=True))
        # Add new columns as nullable first to populate them
        batch_op.add_column(sa.Column('immatriculation', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('type_vehicule', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('autre_type_vehicule', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_mise_circulation', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('kilometrage_actuel', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('numero_chassis', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('couleur', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('annee_fabrication', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('carburant', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sous_statut_principale', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sous_statut_technique', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sous_statut_exceptionnel', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('capacite_reservoir', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ref_pneu_av', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ref_pneu_ar', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('numero_moteur', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('compteur_huile', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('compteur_filtre', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('detenteur', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('numero_serie_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('valeur_acquisition', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('anciennete', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cout_entretien_annuel', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('observations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('num_ancienne_carte_carburant', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('num_nouvelle_carte_carburant', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('code_nouvelle_carte_carburant', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('porteur_carte_carburant', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('card_holder_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_expiration_carburant', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('conducteur_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('service_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('puissance',
               existing_type=sa.INTEGER(),
               nullable=True)

    # Manual Data Migration
    op.execute("UPDATE vehicles SET immatriculation = matricule")
    op.execute("UPDATE vehicles SET type_vehicule = type")
    op.execute("UPDATE vehicles SET date_mise_circulation = date_mise_en_circulation")
    op.execute("UPDATE vehicles SET kilometrage_actuel = kilometrage")
    
    # Apply NOT NULL constraints after population
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.alter_column('immatriculation', nullable=False)
        batch_op.alter_column('type_vehicule', nullable=False)
        batch_op.alter_column('date_mise_circulation', nullable=False)
        
        batch_op.drop_constraint('vehicles_matricule_key', type_='unique')
        batch_op.create_unique_constraint(None, ['immatriculation'])

        batch_op.create_foreign_key(None, 'drivers', ['conducteur_id'], ['id'])
        batch_op.drop_column('affectation')
        batch_op.drop_column('image')
        batch_op.drop_column('date_mise_en_circulation')
        batch_op.drop_column('matricule')
        batch_op.drop_column('type')
        batch_op.drop_column('kilometrage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kilometrage', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('matricule', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date_mise_en_circulation', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('affectation', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('vehicles_matricule_key', ['matricule'])
        batch_op.alter_column('puissance',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('notes')
        batch_op.drop_column('service_id')
        batch_op.drop_column('conducteur_id')
        batch_op.drop_column('date_expiration_carburant')
        batch_op.drop_column('card_holder_name')
        batch_op.drop_column('porteur_carte_carburant')
        batch_op.drop_column('code_nouvelle_carte_carburant')
        batch_op.drop_column('num_nouvelle_carte_carburant')
        batch_op.drop_column('num_ancienne_carte_carburant')
        batch_op.drop_column('observations')
        batch_op.drop_column('cout_entretien_annuel')
        batch_op.drop_column('anciennete')
        batch_op.drop_column('valeur_acquisition')
        batch_op.drop_column('numero_serie_type')
        batch_op.drop_column('detenteur')
        batch_op.drop_column('compteur_filtre')
        batch_op.drop_column('compteur_huile')
        batch_op.drop_column('numero_moteur')
        batch_op.drop_column('ref_pneu_ar')
        batch_op.drop_column('ref_pneu_av')
        batch_op.drop_column('capacite_reservoir')
        batch_op.drop_column('sous_statut_exceptionnel')
        batch_op.drop_column('sous_statut_technique')
        batch_op.drop_column('sous_statut_principale')
        batch_op.drop_column('carburant')
        batch_op.drop_column('annee_fabrication')
        batch_op.drop_column('couleur')
        batch_op.drop_column('numero_chassis')
        batch_op.drop_column('kilometrage_actuel')
        batch_op.drop_column('date_mise_circulation')
        batch_op.drop_column('autre_type_vehicule')
        batch_op.drop_column('type_vehicule')
        batch_op.drop_column('immatriculation')
        batch_op.drop_column('image_128')

    # ### end Alembic commands ###
