"""sync maintenance schema adding missing columns

Revision ID: eab2f634a829
Revises: 1c808e5833be
Create Date: 2026-02-03 08:23:55.075384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab2f634a829'
down_revision = '1c808e5833be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add new columns as nullable first
    with op.batch_alter_table('maintenances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_demande', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_prevue', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('priorite', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('prochain_entretien_km', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('localisation', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('technicien', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cout_estime', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('notes_supplementaires', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('compte_rendu', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date_realisation', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('pieces_remplacees', sa.Text(), nullable=True))

    # 2. Data Migration: Copy 'date' to 'date_demande' and 'date_prevue'
    op.execute("UPDATE maintenances SET date_demande = date, date_prevue = date")

    # 3. Alter columns to be non-nullable and drop old 'date'
    with op.batch_alter_table('maintenances', schema=None) as batch_op:
        batch_op.alter_column('date_demande', nullable=False)
        batch_op.alter_column('date_prevue', nullable=False)
        batch_op.drop_column('date')

    with op.batch_alter_table('planning', schema=None) as batch_op:
        batch_op.alter_column('date_debut',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('date_fin',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        # Check if start_time and end_time exist before dropping
        # batch_op.drop_column('start_time')
        # batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.alter_column('date_fin',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('date_debut',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('maintenances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('pieces_remplacees')
        batch_op.drop_column('date_realisation')
        batch_op.drop_column('compte_rendu')
        batch_op.drop_column('notes_supplementaires')
        batch_op.drop_column('cout_estime')
        batch_op.drop_column('technicien')
        batch_op.drop_column('localisation')
        batch_op.drop_column('prochain_entretien_km')
        batch_op.drop_column('priorite')
        batch_op.drop_column('date_prevue')
        batch_op.drop_column('date_demande')

    # ### end Alembic commands ###
