"""Remove prochaine_entretien_prevu from maintenance

Revision ID: ff747e9504e6
Revises: 2933eed98a3b
Create Date: 2025-12-19 14:49:05.441061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff747e9504e6'
down_revision = '2933eed98a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenances', schema=None) as batch_op:
        batch_op.drop_column('prochaine_entretien_prevu')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prochaine_entretien_prevu', sa.DATE(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
